version: '3'

services:
  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/home/app
    depends_on:
      - backend
    ulimits:
      core:
        hard: 0
        soft: 0
    command: sh -c 'npm install && npm run dev'

  backend:
    build: ./backend
    container_name: 'backend'
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app
    command: bash -c 'python main.py'
    restart: always

  api:
    container_name: 'api'
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    shm_size: '5gb'
    tty: true
    ports:
      - '8001:8001'
    volumes:
      - ./api:/usr/src/app
    command: bash -c 'python main.py'

  api2:
    container_name: 'api2'
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8002
    shm_size: '5gb'
    tty: true
    ports:
      - '8002:8002'
    volumes:
      - ./api:/usr/src/app
    command: bash -c 'python main.py'

